In [9]:
# Import libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

# Load dataset
iris = pd.read_csv("iris.csv")

# Features and target
X = iris.drop("species", axis=1)   # Change column name if different
y = iris["species"]

# Split dataset (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

# Build Decision Tree model
clf_iris = DecisionTreeClassifier(random_state=42)
clf_iris.fit(X_train, y_train)

# Predictions
y_pred = clf_iris.predict(X_test)

# Evaluation
print("IRIS Dataset Results")
print("Accuracy Score:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

IRIS Dataset Results
Accuracy Score: 1.0
Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [11]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

# Load dataset
drug = pd.read_csv("drug.csv")

# Separate features and target FIRST
X = drug.drop("Drug", axis=1)
y = drug["Drug"]

# Encode only feature columns
X = pd.get_dummies(X)

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Build model
clf_drug = DecisionTreeClassifier(random_state=42)
clf_drug.fit(X_train, y_train)

# Predictions
y_pred = clf_drug.predict(X_test)

# Evaluation
print("Drug Dataset Results")
print("Accuracy Score:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Drug Dataset Results
Accuracy Score: 1.0
Confusion Matrix:
 [[ 6  0  0  0  0]
 [ 0  3  0  0  0]
 [ 0  0  5  0  0]
 [ 0  0  0 11  0]
 [ 0  0  0  0 15]]


In [12]:
# Import additional libraries
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error

# Load dataset
petrol = pd.read_csv("petrol_consumption.csv")

# Features and target
X = petrol.drop("Petrol_Consumption", axis=1)  # Change column name if needed
y = petrol["Petrol_Consumption"]

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

# Build Regression Tree
reg_tree = DecisionTreeRegressor(random_state=42)
reg_tree.fit(X_train, y_train)

# Predictions
y_pred = reg_tree.predict(X_test)

# Evaluation metrics
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

print("\nPetrol Consumption Dataset Results")
print("Mean Absolute Error:", mae)
print("Mean Squared Error:", mse)
print("Root Mean Squared Error:", rmse)


Petrol Consumption Dataset Results
Mean Absolute Error: 94.3
Mean Squared Error: 17347.7
Root Mean Squared Error: 131.7106677532234


In [13]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

# Load dataset
drug = pd.read_csv("drug.csv")

# Encode categorical columns
label_encoders = {}
for column in drug.columns:
    if drug[column].dtype == 'object':
        le = LabelEncoder()
        drug[column] = le.fit_transform(drug[column])
        label_encoders[column] = le

# Split features and target
X = drug.drop('Drug', axis=1)
y = drug['Drug']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

# Build model
clf = DecisionTreeClassifier(criterion='entropy')
clf.fit(X_train, y_train)

# Predictions
y_pred = clf.predict(X_test)

# Evaluation
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 1.0
Confusion Matrix:
 [[ 6  0  0  0  0]
 [ 0  3  0  0  0]
 [ 0  0  5  0  0]
 [ 0  0  0 11  0]
 [ 0  0  0  0 15]]
